
version: 0.1

phases:
    install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - echo Build started on `date`
      - apt-get update
      - sudo apt-get install docker
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo ${KEGANENV}
      - docker push keganferreira/demo-aws

