
version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - apt-get update
      - sudo apt-get install docker
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo ${KEGANENV}
      - docker build -t demo-aws .
      - docker tag demo-aws:latest keganferreira/demo-aws:latest
      - docker push keganferreira/demo-aws

