
version: 0.1

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 988965997364.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - apt-get update
      - sudo apt-get install docker
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo ${KEGANENV}
      - docker build -t kegf .
      - docker tag kegf:latest 988965997364.dkr.ecr.ap-southeast-2.amazonaws.com/kegf:latest
      - docker push 988965997364.dkr.ecr.ap-southeast-2.amazonaws.com/kegf:latest

